### ISSUE TITLE
Why would SSVM create wrappers for every function?

### ISSUE THREAD

**Issue by elliott-wen** [second-state/SSVM#155]
Hi, 

Thanks for sharing such a nice project.

I was having a look at the AOT compiler and noticed that a wrapper is created for each WebAssembly function.

I am wondering what is the motivation behind this? 

Cheers

**Comment by hydai** [comment]
Thanks for your question :)

Because we use the LLVM framework to do the AOT compilation, it uses the default calling convert mechanism. If we don't create a wrapper to call these wasm function from the C++ side, we have to provide low-level assemblies which represent the same functionalities to tell it how to associate the function arguments with the registers.

**Comment by elliott-wen** [comment]
Thanks for your answer.

I am still a bit confused. The Aot compiler generates a so/dll object. wouldnt it automatically follow some sort of calling conventions (like x64 fast call convention)?

**Comment by hydai** [comment]
The wrappers are called by the `ssvm runner` which loads the `so/dll`.

The fast call convention will be applied if it's an internal call. For example, wasm function A calls wasm function B.

**Comment by elliott-wen** [comment]
Thanks so much! 

Suppose a wasm function has a prototype int foo(int a, int b).

what would happen if I do the dlopen manually, get the handle of that function (non-wrapper one), cast it to (int)*(int a, int b) and invoke it?

**Comment by ibmibmibm** [comment]
> Thanks so much! Suppose a wasm function has a prototype int foo(int a, int b). what would happen if I do the dlopen manually, get the handle of that function (non-wrapper one), cast it to (int)*(int a, int b) and invoke it?
That compiled wasm function will correctly being invoked by the way you mention.
