### ISSUE TITLE
TypeError: vm.Run is not a function

### ISSUE THREAD

**Issue by cs686** [second-state/SSVM#37]
Hi, I just pass Uint8Array, but got `TypeError: vm.Run is not a function`

![image](https://user-images.githubusercontent.com/11469578/89137441-b3528200-d56a-11ea-8e7e-fe4d8a181e5c.png)

**Comment by hydai** [comment]
Hi @cs686,

This issue is related to [SSVM-NAPI](https://github.com/second-state/ssvm-napi). Please move forward to the there for more question.

And there is no `vm.Run` function in our SSVM-NAPI. Here is the API methods we have: https://github.com/second-state/ssvm-napi#methods

SSVM-NAPI provides three `Run<Type>` functions where the <Type> depends on your return value type. And all of these three `Run<Type>` functions support `Uint8Array` as arguments.

**Comment by cs686** [comment]
@hydai OK,thanks

**Comment by hydai** [comment]
Hi @cs686, 
I released ssvm-napi@0.4.10, which supports `.Run` functions. You can create a rust function without return value now. Let me know if you have any issue with this feature. Thanks :-).
